PROTOCOL_VERSION = "1.0"
PROTOCOL_MAJOR = 1
MAX_FRAME_BYTES = 16_777_216
HEARTBEAT_INTERVAL_SECONDS = 5.0
HEALTH_CHECK_TIMEOUT_SECONDS = 2.0
WORKER_START_TIMEOUT_SECONDS = 10.0
CLIENT_COMMAND_TIMEOUT_SECONDS = 30.0
EVENT_QUEUE_MAXSIZE = 100


